apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # The number of pods this deployment is supposed to create. All the replicas are identical hence replica
  replicas: 1
  # Similar to nodePort usage.
  # is a way of matching the deployment to the pods created by the master. - remember the deployment will tell
  # the kubectl master to create the pods, it doesnt do it itself. So after when changes happen it needs to be able
  # to track which pods the master created so updates get passed. Works the same as nodeport-pod set up. 
  selector:
    matchLabels:
      component: web
  # from here down is pretty much identical to client-pod.yaml
  # Can see how it's building the template all the pods it manages uses
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000